// server
import Script from 'next/script';

import TapPayInit from '@/app/_components/tappay/init';

export const metadata = {
  title: 'tap pay',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <>
      <>{children}</>
      <Script src="https://code.jquery.com/jquery-3.2.1.min.js" />
      <TapPayInit />
    </>
  );
}
