import Script from 'next/script';

import ChakraProvider from '@/app/_components/chakra';
import TapPay from '@/app/_components/tap-pay';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning>
      <body>
        <ChakraProvider>{children}</ChakraProvider>
        <Script
          src="https://code.jquery.com/jquery-3.2.1.min.js"
          integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
          crossorigin="anonymous"
        ></Script>
        <TapPay />
      </body>
    </html>
  );
}
